[pytest]
markers =
    smoke: smoke test cases
    blogs: blogs test cases
    contacts: contacts test cases
    portfolio: portfolio test cases
    technology: technology test cases
    vertical: vertical test cases
  

 -m